### ISSUE TITLE
Glitch with Tic Tac Toe

### ISSUE THREAD

**Issue by Asuka-Kazama** [SlithyMatt/xci_tictactoe#1]
When playing Tic T ac Toe, was starting on the side, after 6 moves on the 7th move (it being my turn), I was unable to place any X's down (shall try to recreate the glitch again).

Isue just happend again, but when I started at the bottom right corner. I placed the X at the bottom right, the cpu placed the O in the middle. I clicked on the O and the X (like the 1st time) and was unable to place any X's. Okay, it happens (when I test it with the bottom right corner), if I click on the X I placed (after the CPU places its O) then I am unable to place any X's down. Okay, I found out, it only happens at the bottom right corner (no matter where you start), if you click the X at the bottom right corner that is already placed, you will be unable to place anymore X's.

**Comment by Asuka-Kazama** [comment]
Another issue: if you Exit from the file menu, and return to BASIC and type run to play again, it is "frozen" at a filled board with the title name behind it. You can do nothing.

**Comment by SlithyMatt** [comment]
The second one is a bug with the XCI engine itself. The graceful exit does not reset all the memory. If you just RUN again, the initial state of the engine is not reloaded, so I'll need to force that. If you want, go ahead an post a bug on the engine: https://github.com/SlithyMatt/x16-xci/issues

**Comment by SlithyMatt** [comment]
Fixed in latest commit. Will be part of next beta release. Workaround for beta 0.2: don't click on occupied cells.
